# Generated by Django 4.1.1 on 2023-04-15 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8ccac958-58cd-4da1-ac6d-44a7433e5f55'), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8ccac958-58cd-4da1-ac6d-44a7433e5f55'), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8ccac958-58cd-4da1-ac6d-44a7433e5f55'), editable=False),
        ),
    ]
